dependencies:
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.1
  - OpenZeppelin/openzeppelin-contracts@4.8.1
compiler:
  solc:
    remappings:
      - "@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.1/contracts"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.1"
networks:
  default: development
  kovan:
    verify: True
  rinkeby:
    verify: True
  hardhat:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
